name: Docker Image CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y9f8h9z3

      - name: Build, tag and push the Docker image
        run: |
          docker build -t fredi7/php-continuous-image . 
          docker tag fredi7/php-continuous-image:latest public.ecr.aws/y9f8h9z3/fredi7/php-continuous-image:latest
          docker push public.ecr.aws/y9f8h9z3/fredi7/php-continuous-image:latest
